### ISSUE TITLE
打包依赖失败

### ISSUE THREAD

**Issue by Shany100** [fex-team/fis3-packager-deps-pack#2]
fis-conf.js 里的代码：

```
fis.match('*.jsx', {
  parser: fis.plugin('babel'),
  rExt: 'js'
})

fis.match('::packager', {
  packager: fis.plugin('deps-pack', {
    'pkg/deps-app.js': [
      // 将 app.jsx 加入队列
      '/module/app.jsx',
      // app.jsx 的所有同步依赖加入队列
      '/module/app.jsx:deps'
    ]
  })
});
```

执行后报错了：

```
[ERROR] Cannot set property 'lastIndex' of undefined

 [DEBUG] 16:14:54.676 TypeError: Cannot set property 'lastIndex' of undefined
    at /usr/local/lib/node_modules/fis3-packager-deps-pack/index.js:80:21
    at Array.filter (native)
    at find (/usr/local/lib/node_modules/fis3-packager-deps-pack/index.js:79:22)
    at /usr/local/lib/node_modules/fis3-packager-deps-pack/index.js:128:20
    at Array.forEach (native)
    at /usr/local/lib/node_modules/fis3-packager-deps-pack/index.js:116:14
    at Array.forEach (native)
    at module.exports (/usr/local/lib/node_modules/fis3-packager-deps-pack/index.js:100:21)
    at cb (/usr/local/lib/node_modules/fis3/lib/release.js:153:5)
    at /usr/local/lib/node_modules/fis3/lib/util.js:1079:9
```

想了解下时什么原因？

**Comment by 2betop** [comment]
不能重现！771245261 私聊。

**Comment by Shany100** [comment]
打印的部分信息：

```
pack:  { 'pkg/deps-app.js': [ '/module/app.js', '/module/app.js:deps' ],
  __plugin: 'deps-pack',
  __name: 'deps-pack',
  __pos: undefined }
```

不知道是不是和 undefined 有关。
升级 fis3 版本 从 3.1.0 到 3.2.4 就 OK 了。

**Comment by 2betop** [comment]
嗯好
